import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Book of answer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          환영합니다 <a href="https://nextjs.org"> <br /> 만나서 반갑습니다!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/book">
              <h2>대답의 책 &rarr;</h2>
              <p>고민의 해답을 찾아보세요</p>
            </Link>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} Test
        </a>
      </footer>
    </div>
  )
}
